### ISSUE TITLE
thanks for more detailed info

### ISSUE THREAD

**Issue by icesmartjuan** [niespodd/browser-fingerprinting#6]
Hi @niespodd ,

Great summary on browser-fp!
would you please share more details on the anti-anti-bot solution `Specialized bot software that targets the unique detection surface of the target website`  ? 
<img width="1061" alt="image" src="https://user-images.githubusercontent.com/37887450/167241573-d30c1557-31c7-48d2-8086-bbb9954f4f82.png">

looking forward to your comments, thank you!

**Comment by niespodd** [comment]
Hi @icesmartjuan,

Let me use two examples. 

Let's assume that the site you want to scrape uses Distil Networks protection. By doing some finished work on reverse engineering the fingerprinting script. Because it's written in JavaScript, you can determine the detection surface quite precisely. An example of such a solution can be found [here](https://github.com/chris124567/puppeteer-bypassing-bot-detection/blob/master/apply-evasions.js).

Many websites use Recaptcha/hCaptcha to limit bot traffic. For example, Alibaba asks for a solution when logging into an account. Until recently, after passing the captcha gate, the logged-in user session was not limited by the number of requests on the site. It was therefore sufficient to "manually" generate session tokens (create and sign in with an account) and then (without changing the IP) use them to scrape at a reasonable rate-limit. 

Generally, such a strategy makes sense when you are targeting a limited number of sites and have the resources to reverse engineer detection scripts. However, you have to reckon with the fact that every time you change a detection script, your solution will be prone to detection.

**Comment by icesmartjuan** [comment]
I see, much appreciated @niespodd
